fp32-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
avx-fp32-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: avx-fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
bf16-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
int8-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
avx-int8-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: avx-int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
bf32-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
fp32-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
avx-fp32-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: avx-fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
bf16-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
int8-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
avx-int8-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: avx-int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
bf32-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
fp32-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
avx-fp32-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: avx-fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
bf16-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
int8-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
avx-int8-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: avx-int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
bf32-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
