fp32-training-phase1:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-training
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    BERT_MODEL_CONFIG: /localdisk/bert_config.json
    OUTPUT_DIR: /tmp
    TRAIN_SCRIPT: /workspace/pytorch-bert-large-training/run_pretrain_mlperf.py
    DATASET_DIR: /pytorch/tfrecord_dir/bert_results4_dataset/
    TRAINING_PHASE: '1'
    DDP: 'false'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /localdisk/bert_config.json
      dst: /localdisk/bert_config.json
    - src: /tmp
      dst: /tmp
    - src: /pytorch/tfrecord_dir/bert_results4_dataset/
      dst: /pytorch/tfrecord_dir/bert_results4_dataset/
fp32-training-phase2:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-training
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    BERT_MODEL_CONFIG: /localdisk/bert_config.json
    OUTPUT_DIR: /tmp
    PRETRAINED_MODEL: /tmp/model_save
    TRAIN_SCRIPT: /workspace/pytorch-bert-large-training/run_pretrain_mlperf.py
    DATASET_DIR: /pytorch/tfrecord_dir/bert_results4_dataset/
    TRAINING_PHASE: '2'
    DDP: 'false'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /localdisk/bert_config.json
      dst: /localdisk/bert_config.json
    - src: /tmp/model_save
      dst: /tmp/model_save
    - src: /pytorch/tfrecord_dir/bert_results4_dataset/
      dst: /pytorch/tfrecord_dir/bert_results4_dataset/
bf16-training-phase1:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-training
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    BERT_MODEL_CONFIG: /localdisk/bert_config.json
    OUTPUT_DIR: /tmp
    TRAIN_SCRIPT: /workspace/pytorch-bert-large-training/run_pretrain_mlperf.py
    DATASET_DIR: /pytorch/tfrecord_dir/bert_results4_dataset/
    TRAINING_PHASE: '1'
    DDP: 'false'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /localdisk/bert_config.json
      dst: /localdisk/bert_config.json
    - src: /tmp
      dst: /tmp
    - src: /pytorch/tfrecord_dir/bert_results4_dataset/
      dst: /pytorch/tfrecord_dir/bert_results4_dataset/
bf16-training-phase2:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-training
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    BERT_MODEL_CONFIG: /localdisk/bert_config.json
    OUTPUT_DIR: /tmp
    PRETRAINED_MODEL: /tmp/model_save
    TRAIN_SCRIPT: /workspace/pytorch-bert-large-training/run_pretrain_mlperf.py
    DATASET_DIR: /pytorch/tfrecord_dir/bert_results4_dataset/
    TRAINING_PHASE: '2'
    DDP: 'false'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /localdisk/bert_config.json
      dst: /localdisk/bert_config.json
    - src: /tmp/model_save
      dst: /tmp/model_save
    - src: /pytorch/tfrecord_dir/bert_results4_dataset/
      dst: /pytorch/tfrecord_dir/bert_results4_dataset/
bf32-training-phase1:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-training
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf32
    BERT_MODEL_CONFIG: /localdisk/bert_config.json
    OUTPUT_DIR: /tmp
    TRAIN_SCRIPT: /workspace/pytorch-bert-large-training/run_pretrain_mlperf.py
    DATASET_DIR: /pytorch/tfrecord_dir/bert_results4_dataset/
    TRAINING_PHASE: '1'
    DDP: 'false'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /localdisk/bert_config.json
      dst: /localdisk/bert_config.json
    - src: /tmp
      dst: /tmp
    - src: /pytorch/tfrecord_dir/bert_results4_dataset/
      dst: /pytorch/tfrecord_dir/bert_results4_dataset/
bf32-training-phase2:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-training
  cmd: quickstart/run_bert_pretrain_phase2.sh bf32
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf32
    BERT_MODEL_CONFIG: /localdisk/bert_config.json
    OUTPUT_DIR: /tmp
    PRETRAINED_MODEL: /tmp/model_save
    TRAIN_SCRIPT: /workspace/pytorch-bert-large-training/run_pretrain_mlperf.py
    DATASET_DIR: /pytorch/tfrecord_dir/bert_results4_dataset/
    TRAINING_PHASE: '2'
    DDP: 'false'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /localdisk/bert_config.json
      dst: /localdisk/bert_config.json
    - src: /tmp/model_save
      dst: /tmp/model_save
    - src: /pytorch/tfrecord_dir/bert_results4_dataset/
      dst: /pytorch/tfrecord_dir/bert_results4_dataset/
avx-fp32-training-phase1:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-training
  cmd: bash run_model.sh avx
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-fp32
    BERT_MODEL_CONFIG: /localdisk/bert_config.json
    OUTPUT_DIR: /tmp
    TRAIN_SCRIPT: /workspace/pytorch-bert-large-training/run_pretrain_mlperf.py
    DATASET_DIR: /pytorch/tfrecord_dir/bert_results4_dataset/
    TRAINING_PHASE: '1'
    DDP: 'false'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /localdisk/bert_config.json
      dst: /localdisk/bert_config.json
    - src: /tmp
      dst: /tmp
    - src: /pytorch/tfrecord_dir/bert_results4_dataset/
      dst: /pytorch/tfrecord_dir/bert_results4_dataset/
avx-fp32-training-phase2:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-training
  cmd: quickstart/run_bert_pretrain_phase2.sh avx-fp32
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-fp32
    BERT_MODEL_CONFIG: /localdisk/bert_config.json
    OUTPUT_DIR: /tmp
    PRETRAINED_MODEL: /tmp/model_save
    TRAIN_SCRIPT: /workspace/pytorch-bert-large-training/run_pretrain_mlperf.py
    DATASET_DIR: /pytorch/tfrecord_dir/bert_results4_dataset/
    TRAINING_PHASE: '1'
    DDP: 'false'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /localdisk/bert_config.json
      dst: /localdisk/bert_config.json
    - src: /tmp/model_save
      dst: /tmp/model_save
    - src: /pytorch/tfrecord_dir/bert_results4_dataset/
      dst: /pytorch/tfrecord_dir/bert_results4_dataset/
