model:                                               # mandatory. lpot uses this model name and framework name to decide where to save tuning history and deploy yaml.
  name: resnet50_v1
  framework: tensorflow                              # mandatory. supported tf_2012_values are tensorflow, pytorch, or mxnet; allow new framework backend extension.

quantization:                                        # optional. tuning constraints on model-wise for advance user to reduce tuning space.
  calibration:
    sampling_size: 50, 100                           # optional. default tf_2012_value is the size of whole dataset. used to set how many portions of calibration dataset is used. exclusive with iterations field.
    dataloader:
      batch_size: 32
      dataset:
        Imagenet:
          root: tf_2012_val         # NOTE: modify to calibration dataset location if needed
      transform:
        ParseDecodeImagenet:
        ResizeCropImagenet: 
          height: 224
          width: 224
  model_wise:                                        # optional. tuning constraints on model-wise for advance user to reduce tuning space.
    activation:
      algorithm: minmax

evaluation:                                          # optional. required if user doesn't provide etf_2012_val_func in lpot.Quantization.
  accuracy:                                          # optional. required if user doesn't provide etf_2012_val_func in lpot.Quantization.
    metric:
      topk: 1                                        # built-in metrics are topk, map, f1, allow user to register new metric.
    dataloader:
      batch_size: 32
      dataset:
        Imagenet:
          root: tf_2012_val          # NOTE: modify to etf_2012_valuation dataset location if needed
      transform:
        ParseDecodeImagenet:
        ResizeCropImagenet: 
          height: 224
          width: 224
  performance:                                       # optional. used to benchmark performance of passing model.
    iteration: 100
    configs:
      cores_per_instance: 4
      num_of_instance: 7
    dataloader:
      batch_size: 32
      dataset:
        Imagenet:
          root: tf_2012_val          # NOTE: modify to etf_2012_valuation dataset location if needed
      transform:
        ParseDecodeImagenet:
        BilinearImagenet:
          height: 224
          width: 224

tuning:
  accuracy_criterion:
    relative:  0.01                                  # optional. default tf_2012_value is relative, other tf_2012_value is absolute. this example allows relative accuracy loss: 1%.
  exit_policy:
    timeout: 0                                       # optional. tuning timeout (seconds). default tf_2012_value is 0 which means early stop. combine with max_trials field to decide when to exit.
  random_seed: 9527                                  # optional. random seed for deterministic tuning.
