releases:
    versioned:
        tag_specs:
            - "{_TAG_PREFIX}{intel-tf}{language-modeling}{mpi-horovod}{bert-large-fp32-training}"
slice_sets:

    bert-large-fp32-training:
        - add_to_name: "-bert-large-fp32-training"
          dockerfile_subdirectory: "model_containers"
          partials:
              - python-build
              - model_package
              - entrypoint
          documentation:
            - name: README.md
              uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32
              text_replace:
                <mode>: training
                <model name>: BERT Large
                <precision>: FP32
                <use case>: language_modeling
                <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_7_0/bert-large-fp32-training.tar.gz
                <package name>: bert-large-fp32-training.tar.gz
                <package dir>: bert-large-fp32-training
                <docker image>: intel/language-modeling:tf-latest-bert-large-fp32-training
              docs:
                - name: Title
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/title.md
                - name: Description
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/description.md
                - name: Download link
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/download.md
                - name: Datasets
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/datasets.md
                - name: Quick Start Scripts
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/quickstart.md
                - name: Bare Metal
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/baremetal.md
                - name: Docker
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/docker.md
                - name: License link
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/license.md
            - docs:
              - name: Title
                uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/title.md
              - name: Description
                uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/description.md
              - name: Datasets
                uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/datasets.md
              - name: Quick Start Scripts
                uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/quickstart.md
              - name: AI Kit
                uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32/.docs/aikit.md
              - name: Resources
                uri: models/quickstart/common/.docs/resources_with_portal_link.md
              name: README.md
              text_replace:
                <mode>: training
                <model name>: BERT Large
                <precision>: FP32
                <use case>: language_modeling
                <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/bert-large-fp32-training-tensorflow-container.html
              uri: models/benchmarks/language_modeling/tensorflow/bert_large/training/fp32
            - docs:
              - name: Title
                uri: models/quickstart/common/.docs/advanced/title.md
              - name: Description
                uri: models/quickstart/common/.docs/advanced/description.md
              - name: Setup
                uri: models/quickstart/common/.docs/advanced/setup.md
              - name: Docker arg
                uri: models/quickstart/common/.docs/advanced/docker_arg.md
              - name: Launch benchmark instructions
                uri: models/benchmarks/language_modeling/tensorflow/bert_large/training/fp32/.docs/advanced/launch_benchmark_instructions.md
              name: Advanced.md
              text_replace:
                <mode>: training
                <model name>: BERT Large
                <precision>: FP32
                <use case>: language_modeling
                <docker image>: 'intel/intel-optimized-tensorflow:latest'
              uri: models/benchmarks/language_modeling/tensorflow/bert_large/training/fp32
          args:
              - PACKAGE_NAME=bert-large-fp32-training
          files:
              - source: benchmarks/common
                destination: benchmarks/common
              - source: benchmarks/launch_benchmark.py
                destination: benchmarks/launch_benchmark.py
              - source: benchmarks/language_modeling/tensorflow/bert_large
                destination: benchmarks/language_modeling/tensorflow/bert_large
              - source: models/language_modeling/tensorflow/bert_large/training/fp32
                destination: ./models/language_modeling/tensorflow/bert_large/training/fp32
              - source: quickstart/language_modeling/tensorflow/bert_large/training/cpu/fp32
                destination: quickstart
              - source: quickstart/common
                destination: quickstart/common
