fp32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
avx-fp32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: avx-fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
bf16-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
int8-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
avx-int8-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: avx-int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
bf32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/\
    - src: /tmp
      dst: /tmp
fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
avx-fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: avx-fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
bf16-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
int8-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
avx-int8-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: avx-int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
bf32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
fp32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
avx-fp32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: avx-fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
bf16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
int8-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
avx-int8-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: avx-int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
bf32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-inference
  cmd: bash run_model.sh
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-inference/
    TEST_MODE: ACCURACY
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-inference/
      dst: /pytorch/pretrained_models/ssd-resnet34-inference/
    - src: /tmp
      dst: /tmp
