b0-flex170-bs128-batch-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-efficientnet-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    BATCH_SIZE: '128'
    MODEL_NAME: EfficientNetB0
    OUTPUT_DIR: /tmp
  volumes:
    - src: /tmp
      dst: /tmp
b3-flex170-bs128-batch-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-efficientnet-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    BATCH_SIZE: '128'
    MODEL_NAME: EfficientNetB3
    OUTPUT_DIR: /tmp
  volumes:
    - src: /tmp
      dst: /tmp
b4-flex170-bs128-batch-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-efficientnet-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    BATCH_SIZE: '128'
    MODEL_NAME: EfficientNetB4
    OUTPUT_DIR: /tmp
  volumes:
    - src: /tmp
      dst: /tmp
