batch-170-int8-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: int8
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_170
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50v1_5-frozen_graph-int8-gpu.pb
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
  volumes:
    - src: /tmp
      dst: /tmp
batch-170-fp16-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: float16
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_170
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
  volumes:
    - src: /tmp
      dst: /tmp
batch-170-bf16-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: bfloat16
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_170
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
  volumes:
    - src: /tmp
      dst: /tmp
batch-170-tf32-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: tensorfloat32
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_170
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
  volumes:
    - src: /tmp
      dst: /tmp
batch-170-fp32-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: float32
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_170
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
  volumes:
    - src: /tmp
      dst: /tmp
batch-140-int8-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_140
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50v1_5-frozen_graph-int8-gpu.pb
    BATCH_SIZE: '256'
    OUTPUT_DIR: /tmp
online-140-int8-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_140
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50v1_5-frozen_graph-int8-gpu.pb
    BATCH_SIZE: '1'
    OUTPUT_DIR: /tmp
batch-140-fp16-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_140
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '256'
    OUTPUT_DIR: /tmp
online-140-fp16-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_140
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '1'
    OUTPUT_DIR: /tmp
batch-140-bf16-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_140
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '256'
    OUTPUT_DIR: /tmp
online-140-bf16-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_140
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '1'
    OUTPUT_DIR: /tmp
batch-140-tf32-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_140
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '256'
    OUTPUT_DIR: /tmp
online-140-tf32-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_140
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '1'
    OUTPUT_DIR: /tmp
batch-140-fp32-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_140
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '256'
    OUTPUT_DIR: /tmp
online-140-fp32-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    TEST_MODE: inference
    FLEX_GPU_TYPE: flex_140
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50_v1.pb
    BATCH_SIZE: '1'
    OUTPUT_DIR: /tmp
accuracy-int8:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: int8
    TEST_MODE: accuracy
    PB_FILE_PATH: /workspace/tf-flex-series-resnet50v1-5-inference/models/pretrained_models/resnet50v1_5-frozen_graph-int8-gpu.pb
    DATASET_DIR: /local_dateset/TF_Imagenet_FullData/
    OUTPUT_DIR: /tmp
  volumes:
    - src: /local_dateset/TF_Imagenet_FullData/
      dst: /local_dateset/TF_Imagenet_FullData/
