fp32-accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: fp32
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: ACCURACY
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
fp32-realtime:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: fp32
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: REALTIME
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
fp32-throughput:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: fp32
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
bf32-accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: bf32
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: ACCURACY
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
bf32-realtime:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: bf32
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: REALTIME
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
bf32-throughput:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: bf32
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
bf16-accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: bf16
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: ACCURACY
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
bf16-realtime:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: bf16
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: REALTIME
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
bf16-throughput:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: bf16
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
avx-fp32-accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: avx-fp32
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: ACCURACY
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
avx-fp32-realtime:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: avx-fp32
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: REALTIME
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
avx-fp32-throughput:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-inference
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: avx-fp32
    CHECKPOINT_DIR: /localdisk/rnnt_model/
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /localdisk/rnnt_model/
      dst: /localdisk/rnnt_model/
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
    - src: /tmp
      dst: /tmp
