package:
  name: "dataset_librarian"
  version: "1.0.4"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataset_librarian-{{ version }}.tar.gz
  sha256: d969f7eac1459e052d6f4e1ed541e3daf5184b260081ae9edcb2f54bc7a69544

build:
  noarch: python
  script: |
    {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.11
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >=3.9,<3.11
    - pandas
    - tqdm
    - docx2txt
    - openpyxl
    - pillow
    - scikit-learn-intelex
    - python-dotenv
    - wget

test:
  imports:
    - dataset_librarian

about:
  summary: Dataset librarian is a tool to download and apply the preprocessing needed for the list of supported datasets
  license: 'APACHE'
  about_license_url: https://www.apache.org/licenses/LICENSE-2.0.html
  home: "https://github.com/IntelAI/models/tree/master/datasets/dataset_api"
