fp32-training-perf:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-training
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: fp32
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-training
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    THROUGHPUT: 'true'
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-training
      dst: /pytorch/pretrained_models/ssd-resnet34-training
    - src: /tmp
      dst: /tmp
fp32-training-accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-training
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: fp32
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-training
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-training
      dst: /pytorch/pretrained_models/ssd-resnet34-training
    - src: /tmp
      dst: /tmp
bf16-training-perf:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-training
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: bf16
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-training
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-training
      dst: /pytorch/pretrained_models/ssd-resnet34-training
    - src: /tmp
      dst: /tmp
bf16-training-accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-training
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: bf16
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-training
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-training
      dst: /pytorch/pretrained_models/ssd-resnet34-training
    - src: /tmp
      dst: /tmp
bf32-training-perf:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-training
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: bf32
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-training
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-training
      dst: /pytorch/pretrained_models/ssd-resnet34-training
    - src: /tmp
      dst: /tmp
bf32-training-accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-training
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: bf32
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-training
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-training
      dst: /pytorch/pretrained_models/ssd-resnet34-training
    - src: /tmp
      dst: /tmp
avx-fp32-training-perf:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-training
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: avx-fp32
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-training
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-training
      dst: /pytorch/pretrained_models/ssd-resnet34-training
    - src: /tmp
      dst: /tmp
avx-fp32-training-accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-ssd-resnet34-training
  cmd: bash run_model.sh
  shm-size: 8G
  env:
    PRECISION: avx-fp32
    CHECKPOINT_DIR: /pytorch/pretrained_models/ssd-resnet34-training
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/ssd-resnet34-training
      dst: /pytorch/pretrained_models/ssd-resnet34-training
    - src: /tmp
      dst: /tmp
