fp32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-training
  cmd: bash run_model.sh
  env:
    PRECISION: fp32
    BATCH_SIZE: '112'
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /tmp
      dst: /tmp
avx-fp32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-training
  cmd: bash run_model.sh
  env:
    PRECISION: avx-fp32
    BATCH_SIZE: '112'
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /tmp
      dst: /tmp
bf16-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-training
  cmd: bash run_model.sh
  env:
    PRECISION: bf16
    BATCH_SIZE: '112'
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /tmp
      dst: /tmp
bf32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-training
  cmd: bash run_model.sh
  env:
    PRECISION: bf32
    BATCH_SIZE: '112'
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /tmp
      dst: /tmp
