fp32-performance-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-recommendation-dlrm-v2-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /tmp
      dst: /tmp
fp32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-recommendation-dlrm-v2-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    DATASET_DIR: /localdisk/pytorch_dataset/dlrm_v2/dataset/
    WEIGHT_DIR: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/pytorch_dataset/dlrm_v2/dataset/
      dst: /localdisk/pytorch_dataset/dlrm_v2/dataset/
    - src: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
      dst: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
fp16-performance-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-recommendation-dlrm-v2-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /tmp
      dst: /tmp
fp16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-recommendation-dlrm-v2-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp16
    DATASET_DIR: /localdisk/pytorch_dataset/dlrm_v2/dataset/
    WEIGHT_DIR: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/pytorch_dataset/dlrm_v2/dataset/
      dst: /localdisk/pytorch_dataset/dlrm_v2/dataset/
    - src: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
      dst: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
bf16-performance-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-recommendation-dlrm-v2-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /tmp
      dst: /tmp
bf16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-recommendation-dlrm-v2-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    DATASET_DIR: /localdisk/pytorch_dataset/dlrm_v2/dataset/
    WEIGHT_DIR: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/pytorch_dataset/dlrm_v2/dataset/
      dst: /localdisk/pytorch_dataset/dlrm_v2/dataset/
    - src: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
      dst: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
int8-performance-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-recommendation-dlrm-v2-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
  volumes:
    - src: /tmp
      dst: /tmp
int8-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-recommendation-dlrm-v2-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8
    DATASET_DIR: /localdisk/pytorch_dataset/dlrm_v2/dataset/
    WEIGHT_DIR: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/pytorch_dataset/dlrm_v2/dataset/
      dst: /localdisk/pytorch_dataset/dlrm_v2/dataset/
    - src: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
      dst: /localdisk/pytorch_dataset/dlrm_v2/model_weights/
