fp32-online-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
bf32-online-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf32
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
bf32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf32
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
int8-online-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
int8-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
bf16-online-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
bf16-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
avx-int8-online-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-int8
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
avx-int8-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-int8
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
avx-fp32-online-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-fp32
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
avx-fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-bert-large-inference
  cmd: bash run_model.sh
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-fp32
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-bert-large-inference/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
