fp32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-recommendation-dlrm-training-${BASE_IMAGE_NAME:-ubuntu}
  cmd: sh -c "cd models_v2/pytorch/dlrm/training/cpu && ./run_model.sh"
  shm-size: 10G
  env:
    PRECISION: fp32
    NUM_BATCH: '10000'
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/spr_dlrm_preprocessed/dlrm
  volumes:
    - src: /pytorch/spr_dlrm_preprocessed/dlrm
      dst: /pytorch/spr_dlrm_preprocessed/dlrm
    - src: /tmp
      dst: /tmp
bf16-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-recommendation-dlrm-training-${BASE_IMAGE_NAME:-ubuntu}
  cmd: sh -c "cd models_v2/pytorch/dlrm/training/cpu && ./run_model.sh"
  shm-size: 10G
  env:
    PRECISION: bf16
    NUM_BATCH: '10000'
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/spr_dlrm_preprocessed/dlrm
  volumes:
    - src: /pytorch/spr_dlrm_preprocessed/dlrm
      dst: /pytorch/spr_dlrm_preprocessed/dlrm
    - src: /tmp
      dst: /tmp
bf32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-recommendation-dlrm-training-${BASE_IMAGE_NAME:-ubuntu}
  cmd: sh -c "cd models_v2/pytorch/dlrm/training/cpu && ./run_model.sh"
  shm-size: 10G
  env:
    PRECISION: bf32
    NUM_BATCH: '10000'
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/spr_dlrm_preprocessed/dlrm
  volumes:
    - src: /pytorch/spr_dlrm_preprocessed/dlrm
      dst: /pytorch/spr_dlrm_preprocessed/dlrm
    - src: /tmp
      dst: /tmp
