fp32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-training
  cmd: bash run_model.sh
  ipc: host
  env:
    PRECISION: fp32
    CHECKPOINT_DIR: /localdisk/rnnt_model
    OUTPUT_DIR: /tmp
    RESULT_DIR: /tmp
    NUM_STEPS: '100'
    DATASET_DIR: /pytorch/rnnt_dataset_training
  volumes:
    - src: /pytorch/rnnt_dataset_training
      dst: /pytorch/rnnt_dataset_training
    - src: /localdisk/rnnt_model
      dst: /localdisk/rnnt_model
    - src: /tmp
      dst: /tmp
bf16-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-training
  cmd: bash run_model.sh
  ipc: host
  env:
    PRECISION: bf16
    CHECKPOINT_DIR: /localdisk/rnnt_model
    OUTPUT_DIR: /tmp
    RESULT_DIR: /tmp
    NUM_STEPS: '100'
    DATASET_DIR: /pytorch/rnnt_dataset_training
  volumes:
    - src: /pytorch/rnnt_dataset_training
      dst: /pytorch/rnnt_dataset_training
    - src: /localdisk/rnnt_model
      dst: /localdisk/rnnt_model
    - src: /tmp
      dst: /tmp
bf32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-training
  cmd: bash run_model.sh
  ipc: host
  env:
    PRECISION: bf32
    CHECKPOINT_DIR: /localdisk/rnnt_model
    OUTPUT_DIR: /tmp
    RESULT_DIR: /tmp
    NUM_STEPS: '100'
    DATASET_DIR: /pytorch/rnnt_dataset_training
  volumes:
    - src: /pytorch/rnnt_dataset_training
      dst: /pytorch/rnnt_dataset_training
    - src: /localdisk/rnnt_model
      dst: /localdisk/rnnt_model
    - src: /tmp
      dst: /tmp
