fp32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: REALTIME
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
fp32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
fp16-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: REALTIME
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
fp16-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
fp16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
bf16-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: REALTIME
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
bf16-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
bf16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
int8-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: REALTIME
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
int8-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
int8-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
    DATASET_DIR: /localdisk/yolov7_data
    CHECKPOINT_DIR: /localdisk/yolov7_model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/yolov7_data
      dst: /localdisk/yolov7_data
    - src: /localdisk/yolov7_model
      dst: /localdisk/yolov7_model
