header: |
    # Copyright (c) 2020-2021 Intel Corporation
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # ============================================================================
    #
    # THIS IS A GENERATED DOCKERFILE.
    #
    # This file was assembled from multiple pieces, whose use is documented
    # throughout. Please refer to the TensorFlow dockerfiles documentation
    # for more information.

# A combinatorial explosion of Docker images and Dockerfiles.
# Each "release" defines all of the ways to combine related but separate chunks
# of functionality ("slices") by listing all of the "slice sets" to use when
# building.
releases:
    versioned:
        is_dockerfiles: false
        tag_specs: []

slice_sets:

    intel-tf:
        - add_to_name: ""

    mpi-horovod:
        - add_to_name: ""
          args:
              - PY_VERSION=3.8

    image-recognition:
        - add_to_name: "-image-recognition"
          files:
               - source: LICENSE
                 destination: licenses/LICENSE
               - source: third_party
                 destination: licenses/third_party

    image-segmentation:
        - add_to_name: "-image-segmentation"
          files:
               - source: LICENSE
                 destination: licenses/LICENSE
               - source: third_party
                 destination: licenses/third_party

    language-modeling:
        - add_to_name: "-language-modeling"
          files:
               - source: LICENSE
                 destination: licenses/LICENSE
               - source: third_party
                 destination: licenses/third_party

    language-translation:
        - add_to_name: "-language-translation"
          files:
               - source: LICENSE
                 destination: licenses/LICENSE
               - source: third_party
                 destination: licenses/third_party

    object-detection:
        - add_to_name: "-object-detection"
          args:
              - PY_VERSION=3.8
          files:
               - source: LICENSE
                 destination: licenses/LICENSE
               - source: third_party
                 destination: licenses/third_party

    recommendation:
        - add_to_name: "-recommendation"
          files:
               - source: LICENSE
                 destination: licenses/LICENSE
               - source: third_party
                 destination: licenses/third_party

    text-to-speech:
        - add_to_name: "-text-to-speech"
          files:
               - source: LICENSE
                 destination: licenses/LICENSE
               - source: third_party
                 destination: licenses/third_party
