bf16-distributed-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-recommendation-pytorch-max-gpu-dlrmv2-training
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: BF16
    BATCH_SIZE: '65536'
    PLATFORM: Max
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'True'
    DATASET_DIR: /var/torchrec-dlrm-v2
  volumes:
    - src: /var/torchrec-dlrm-v2
      dst: /var/torchrec-dlrm-v2
    - src: /dev/dri
      dst: /dev/dri
    - src: /tmp
      dst: /tmp
fp32-distributed-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-recommendation-pytorch-max-gpu-dlrmv2-training
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: FP32
    BATCH_SIZE: '65536'
    PLATFORM: Max
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'True'
    DATASET_DIR: /var/torchrec-dlrm-v2
  volumes:
    - src: /var/torchrec-dlrm-v2
      dst: /var/torchrec-dlrm-v2
    - src: /dev/dri
      dst: /dev/dri
    - src: /tmp
      dst: /tmp
tf32-distributed-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-recommendation-pytorch-max-gpu-dlrmv2-training
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: TF32
    BATCH_SIZE: '65536'
    PLATFORM: Max
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'True'
    DATASET_DIR: /var/torchrec-dlrm-v2
  volumes:
    - src: /var/torchrec-dlrm-v2
      dst: /var/torchrec-dlrm-v2
    - src: /dev/dri
      dst: /dev/dri
    - src: /tmp
      dst: /tmp
